#!/bin/sh                                                                                           
set -e

root="$(CDPATH= cd -- "$(dirname -- "$0")"/.. && pwd)"
cd "$root"

script/prepare-keychain-and-notarytool &&

mac_version="$(script/version)" &&
build_outputs="$(MAC_VERSION="$mac_version" script/build | tail -n 2)" &&
puzzles_scratch="$(echo "$build_outputs" | head -n 1)" &&
puzzles_app="$(echo "$build_outputs" | head -n 2 | tail -n 1)" &&

puzzles_dmg="$(script/prep-for-distribution-mac "$puzzles_scratch" "$puzzles_app" | tail -n 1)" &&

commit="$(cd "$root" && git rev-parse --short HEAD)" &&
release_version="$mac_version"."$commit" &&
gh release create \
    "$release_version" \
    "$puzzles_dmg" \
    --latest
